<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.8.8</AssemblyVersion>
    <FileVersion>1.8.8</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="PacketDotNet.dll" />
    <None Remove="SharpPcap.dll" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="PacketDotNet.dll" />
    <EmbeddedResource Include="SharpPcap.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PacketDotNet" Version="1.4.8" />
    <PackageReference Include="SharpPcap" Version="6.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RtCli\RtCli.csproj" />
  </ItemGroup>

</Project>
